### ISSUE TITLE
Why exporting reducers as default

### ISSUE THREAD

**Issue by thedanheller** [FortechRomania/react-redux-complete-example#10]
I was wondering if it wouldn't be better to have the operations as a default export, as they are more widely used across the app while the reducers are only imported once, to create the store.

What do you think?

**Comment by alexnm** [comment]
It's an interesting idea. Export reducers as a default is something taken from the original duck proposal. I see your point, we use reducers only once. However, we use operations and selectors most of the time together for defining a container component - selectors respresent the read part, operations represent the write part. So you would most of the times be doing something like:

import { duckOperations, duckSelectors } from <duck>

I think it makes more sense to have them as named exports for keeping this cases consistent.

Furthermore, having the reducers as default allow us to handle all the duck folders automatically once the reducers are exported from the `index.js` file: https://github.com/FortechRomania/react-redux-complete-example/blob/master/src/app/state/store.js

**Comment by thedanheller** [comment]
thanks @alexnm it makes perfect sense
