### ISSUE TITLE
Where is the Redux folder

### ISSUE THREAD

**Issue by ziwer1** [FortechRomania/react-redux-complete-example#19]
Hi, @alexnm 
I just stumbled upon your article at 
https://medium.freecodecamp.org/scaling-your-redux-app-with-ducks-6115955638be
Where is the redux folder mentioned in the article?
Is this repo out of sync with the article?

**Comment by alexnm** [comment]
Hey,

The redux folder from the article is here: https://github.com/FortechRomania/react-redux-complete-example/tree/master/src/app/state/ducks

However, the project is a bit outdated. But the principles behind the redux architecture are the same

**Comment by ejabu** [comment]
What do you mean by outdated ?

I just wanted to start react project by using your boilerplate

**Comment by alexnm** [comment]
the project itself does not use the latest versions of: react, webpack, react-router, etc.
