### ISSUE TITLE
Why do you separate "ducks" so strictly from react

### ISSUE THREAD

**Issue by sir-marc** [FortechRomania/react-redux-complete-example#2]
I just read your post on medium and I really like your approach.
(Expect that i don't like default exports because of typescript)

But I've one question:
You say that you prefer Feature-first over function-first so why do you separate redux so strictly from the React part?
you have something like:
app
|-redux
|    |-cart
|        |-ducks
|-react
    |-cart

For me this is somekind of function-first. The topic is the same (cart vs cart) but you have it a separate places. Why don't you include the ducks folder inside the cart folder in the "react" part? like:
app
|-cart
|   |-styles // for styles for example
|   |-components // for react stuff
|   |-ducks // your redux stuff
|-otherModules

Thanks in advance

**Comment by alexnm** [comment]
We found that components are usually using data from more ducks. For example, the cart needs information about the user, session, products and cart. Then there are components like header, footer, or simply reusable components across the entire app, which don't necessarily belong to a duck/feature.

The way I see it ducks and components can be connected in NxM possibilities

**Comment by sir-marc** [comment]
Yes of course, that's true. But why not just import it from where it is?
I mean the duck clearly belongs to a feature, so why not put it there.
You can still import 'user/duck' from cart or whatever.
Put I see your point, thank you.

**Comment by alexnm** [comment]
I guess it also depends if you're building an website-like or an app-like project. A duck always belongs to a feature, yes, but component not, that's the main reason behind the separation. Layouts, pages, components, enhancers/decorators make more sense grouped by function (for me)

**Comment by sir-marc** [comment]
Thank you for your response and explanation. I can understand your point.
I still think that also a component belongs to a feature although it can be used by other features.
But thank you anyway.

**Comment by alexnm** [comment]
I understand your point of view also, thanks for sharing it and for the feedback.

**Comment by thedanheller** [comment]
For me this view/state separation is great. 

When you're building the UI you think about layout, colors, css, styling, tags, semantics. 
When you're building the state you think in data, information, api calls, promises, callbacks, etc. 

Having this separation in the top level folder really helps me focus on either part of the app.
